version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: wordpress
      MYSQL_USER: aswan
      MYSQL_PASSWORD: 1234
    volumes:
      - db_data:/var/lib/mysql

  wordpress:
    image: wordpress:latest
    container_name: wordpress_container
    restart: always
    expose:
      - "80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: aswan
      WORDPRESS_DB_PASSWORD: 1234
      WORDPRESS_FORCE_SSL_ADMIN: "true"
    volumes:
      - wordpress_data:/var/www/html

  nginx:
    image: nginx
    container_name: nginx_container
    restart: always
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
    depends_on:
      - wordpress

volumes:
  db_data:
  wordpress_data:

